### ISSUE TITLE
FRDM KL25Z

### ISSUE THREAD

**Issue by badabin** [sparkfun/Music_Instrument_Shield#1]
Disclaimer: am an absolute beginner, pardon my misconceptions and assumptions.
I wanted to hookup the musical instrument shield to my kl25z board, Is it possible?

**Comment by badabin** [comment]
``

**Comment by Grahldg** [comment]
Hello, thanks for your question.  It appears that the KL25Z was designed for compatibility with Arduino shields so I would assume it should work, but that is not a product we carry so I'm not able to guarantee compatibility.  If you decide to try it and run into problems you can always contact our [Technical Assistance Team](https://www.sparkfun.com/technical_assistance) for more immediate help.
